@startuml
actor "Visitante" as Visitante

rectangle Sistema {
  usecase "Acessar Página de Login" as UC_AcessarPaginaLogin
  usecase "Inserir Email e Senha" as UC_InserirCredenciais
  usecase "Verificar Credenciais" as UC_VerificarCredenciais
  usecase "Autenticar Usuário" as UC_AutenticarUsuario
  usecase "Redirecionar para Página Inicial" as UC_Redirecionar
  usecase "Exibir Mensagem de Erro" as UC_ExibirErro
}

Visitante --> UC_AcessarPaginaLogin
Visitante --> UC_InserirCredenciais
UC_InserirCredenciais --> UC_VerificarCredenciais
UC_VerificarCredenciais --> UC_AutenticarUsuario : Credenciais Válidas
UC_VerificarCredenciais --> UC_ExibirErro : Credenciais Inválidas
UC_AutenticarUsuario --> UC_Redirecionar
@enduml
