# Generated by Django 5.1.2 on 2024-11-01 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_feedback', models.CharField(choices=[('comentarios_gerais', 'Comentários Gerais'), ('sugestoes_de_melhoria', 'Sugestões de Melhoria'), ('relato_de_erros_ou_problemas_tecnicos', 'Relato de erros ou problemas técnicos')], max_length=50)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_produto', to='perfil.perfil')),
            ],
        ),
    ]
