@startuml
actor "Usuário Autenticado" as UsuarioAutenticado

rectangle Sistema {
  usecase "Acessar Página de Atividades" as UC_AcessarPaginaAtividades
  usecase "Selecionar Tipo de Atividade" as UC_SelecionarTipoAtividade
  usecase "Iniciar Atividade" as UC_IniciarAtividade
  usecase "Coletar Dados da Atividade" as UC_ColetarDadosAtividade
  usecase "Pausar Atividade" as UC_PausarAtividade
  usecase "Parar Atividade" as UC_PararAtividade
  usecase "Calcular Métricas Finais" as UC_CalcularMetricasFinais
  usecase "Salvar Atividade no Histórico" as UC_SalvarAtividade
}

UsuarioAutenticado --> UC_AcessarPaginaAtividades
UsuarioAutenticado --> UC_SelecionarTipoAtividade
UsuarioAutenticado --> UC_IniciarAtividade
UC_IniciarAtividade --> UC_ColetarDadosAtividade
UsuarioAutenticado --> UC_PausarAtividade : <<Opcional>>
UsuarioAutenticado --> UC_PararAtividade
UC_PararAtividade --> UC_CalcularMetricasFinais
UC_CalcularMetricasFinais --> UC_SalvarAtividade
@enduml
