@startuml
actor "Usuário Autenticado" as UsuarioAutenticado

rectangle Sistema {
  usecase "Acessar Página de Dashboard" as UC_AcessarDashboard
  usecase "Coletar Dados de Atividades e Métricas" as UC_ColetarDados
  usecase "Gerar Gráficos e Relatórios" as UC_GerarGraficos
  usecase "Exibir Dashboard com Gráficos e Métricas" as UC_ExibirDashboard
}

UsuarioAutenticado --> UC_AcessarDashboard
UC_AcessarDashboard --> UC_ColetarDados
UC_ColetarDados --> UC_GerarGraficos
UC_GerarGraficos --> UC_ExibirDashboard
@enduml
