@startuml
class ImportadorDadosExterno {
nomeArquivo: str
caminhoArquivo: str
+importarData(): void
}

class AtividadeFisica {
id: int
data: datetime
localizacao: str
tempoTotal: float
tempoMovimento: float
metricas: Metricas
+iniciarAtividade()
+pararAtividade()
+pausarAtividade()
}

class Corrida {
distancia: float
velocidade: float
ritmo: float
elevacao: float
+calcularVelocidade(): float
+calcularRitmo(): float
}

class Ciclismo {
distancia: float
velocidade: floatText
elevacao: float
+calcularVelocidade(): float
}

class Natacao {
  estilo: String
  distancia: float
  tempoPiscina: float
  voltas: int
  +calcularVelocidade(): float
  +calcularRitmo(): float
}


class Historico {
id: int
atividade: AtividadeFisica
usuario: Usuario
+getAtividadeDetalhes(): dict
+getHistoricoUsuario(): list
}

class Metricas {
id: int
nome: str
descricao: str
valor: float
+getMetricData(): dict
}

class Usuario {
id: int
nome: str
idade: int
peso: float
altura: float
email: str
+getAlerts(): list
}

class Gamificacao {
xp: int
level: int
rank: int
+calcularXP(): int
+getRank(): int
}

class Dashboard {
id: int
user: Usuario
+gerarRelatorioSemanal(): dict
+gerarRelatorioMensal(): dict
+getEvolucaoProjecao(): dict
}

AtividadeFisica <|-- Corrida
AtividadeFisica <|-- Ciclismo
AtividadeFisica <|-- Natacao

AtividadeFisica --> Metricas
AtividadeFisica --> Historico
Historico --> Usuario
Usuario --> Gamificacao
Usuario --> Dashboard
ImportadorDadosExterno --> AtividadeFisica
@enduml